<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UserProfiles.Application\UserProfiles.Application.csproj" />
    <ProjectReference Include="..\UserProfiles.Domain\UserProfiles.Domain.csproj" />
  </ItemGroup>
</Project>

